### PR TITLE
Updated Mining Call information

### PR DESCRIPTION
**Pull request by michellebrous**
Added recording link & presentation slides on ipfs

### CODE REVIEW

**Comment by pooja** [comment]
Nice! Should we also add the recording to ipfs? I think we still need a way for Chinese community members to access the recording

**Comment by michellebrous** [comment]
I'm not sure how well the video will work on IPFS given its size. Even adding the presentation to IPFS was a doozy. Have you had a good experience with this @pooja? I think @moyi is going to add this video to our Tencent video account once it is verified

**Comment by pooja** [comment]
If you're pinning to the gateway (by using ipfsbot or similar), I think
it's a gateway (rather than adding to ipfs) issue. But regardless, I'd try
it! Good to know we will also be adding to tencent. But we should dogfood
ipfs! maybe we can add both ipfs and tencent video links so people have
options? I wouldn't block the PR on adding the ipfs link but maybe kick it
off and then you can add the link in later!

**Comment by michellebrous** [comment]
@pooja of course I'd like to use the IPFS / the gateway -- I pinned the video but unfortunately its not loading :(

https://ipfs.io/ipfs/QmQophNZUqSRgJtyJYUGes81hkWfLWeGYc1rbFHvFrFQSE

**Comment by pooja** [comment]
Hey @michellebrous it works for me actually! Want to re-check? Sometimes it takes a little while at first, but then is much faster afterwards. It loaded in <3 seconds for me.

**Comment by pooja** [comment]
Ahh, well the first minute loaded quickly for me and now it's loading. But anyhow it works fine! Can we add the link?

**Comment by michellebrous** [comment]
Ok I added the link. It finally worked for me too. @pooja could you approve so I can merge? Thanks!

**Comment by pooja** [comment]
Yes approved!

**Pull request merged**
