### PR TITLE
[Project Submission] Defi Together

### PR DESCRIPTION
**Pull request by flyingnobita**
@jennijuju Can you please review this PR?

Yes please feature our updates in the Filecoin newsletter.

### CODE REVIEW

**Comment by longfeiWan9** [comment]
@flyingnobita Thank you for submitting the project to Filecoin community. I have left a few comments on the content of your submission. 

Besides that, I am curious how this project is using IPFS or Filecoin to support its features. Could you please add some content in the docs to explain it more so that our community can understand this project better?

**Comment by longfeiWan9** [comment]
@flyingnobita Thank you for adding more details to the project.  It is very helpful for us to understand the project and I think it is a great project overall. 

But after I reviewed it and also looked into the code, I found that your project is using `ipfs-http-client` to update content to IPFS via Infura API, so it is purely using IPFS but not Filecoin. So I think it is probably not right to add your project into Filecoin project showcase. Maybe you should considering submit your project to [IPFS/community](https://github.com/ipfs/community)

**Comment by flyingnobita** [comment]
@longfeiWan9 Thank you for reviewing the request and the code. I understand what you're saying and that it is probably more fitting to apply for the IPFS grant.

At the beginning of the grant application, I didn't know if I should apply to IPFS or Filecoin grant, and I was[ actually suggested ](https://filecoinproject.slack.com/archives/C02A48BJ1SQ/p1629290127011700?thread_ts=1629276469.011600&cid=C02A48BJ1SQ) to apply to Filecoin by your colleague. I guess neither your colleague nor I knew that if the project is only using `ipfs-http-client` (which is the basic requirement for using ceramic), then the application should be to IPFS and not Filecoin.

Thus I'm sorry for wasting your time with this application and if you can kindly let your colleagues know so that future applicants can apply for the right grant.

**Comment by longfeiWan9** [comment]
@flyingnobita Sorry about the confusion. If you have submitted to the IPFS community, could you please also close this issue. 

Thank you.

**Pull request closed without merging**
