### PR TITLE
[Project Submission] Paper House

### PR DESCRIPTION
**Pull request by msanket9**
Our updates can be featured in the Filecoin newsletter!

### CODE REVIEW

**Comment by longfeiWan9** [comment]
@msanket9 nice project. There is one thing needs to be fixed before I can approve it. Coupld you please move the file into `projects\application` folder?

**Comment by longfeiWan9** [comment]
@msanket9 Thank you very much for updating the PR. 

I looked into the code of your project, and see that you are using ipfs-http-client to store and retrieve content from IPFS. Is there anywhere that you are using Filecoin to backup or store content?

**Comment by msanket9** [comment]
We didn't directly use Filecoin to store the contents, but used [NFT.Storage](https://nft.storage) to store all the research papers minted on our platform. NFT.Storage stores on both IPFS and Filecoin.

**Review by longfeiWan9 — APPROVED** [review]

**Comment by longfeiWan9** [comment]
I see. Thank you for explaining that. @msanket9 I will go ahead and approve it.

**Review by longfeiWan9 — APPROVED** [review]

**Pull request merged**
