### PR TITLE
[Project Submission]Filwallet by IPFSForce

### PR DESCRIPTION
**Pull request by timguo-ipfs**

### CODE REVIEW

**Comment by jennijuju** [comment]
umm nothing was commited?

**Comment by timguo-ipfs** [comment]
> umm nothing was commited?

done now, thanks for the reminder. 
we'd like to share it through the NewsLetter.

**Comment by jennijuju** [comment]
Thank you for submitting! please create discussions https://github.com/filecoin-project/community/discussions/categories/project-showcase for giving communities future updates!

**Comment by longfeiWan9** [comment]
@timguo-ipfs I am reviewing the community application submission and notice your PR was submitted early and it does not follow the [project submission template](https://github.com/filecoin-project/community/blob/master/templates/project-submission-template.md). Would you please updated it accordingly it so that I can approve it?

**Comment by longfeiWan9** [comment]
> updated community-readme, add slack channels for venus and forest

@timguo-ipfs can you please submit separate PR for three of your updates:
+ community-readme
+ filscan
+ filwallet

**Pull request closed without merging**
